version: "2"
run:
  modules-download-mode: readonly
linters:
  default: all
  disable:
    - depguard
    - exhaustruct
    - ireturn
    - paralleltest
    - revive
    - rowserrcheck
    - testpackage
    - varnamelen
    - wrapcheck
